### ISSUE TITLE
unit tests involving postgresql fixture started to fail 

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine#193]
GitHub actions unit tests started to fail like so recently. No particular code changes seem to correlate with this error:

```
__________________ ERROR at setup of test_start_from_nothing ___________________
Traceback (most recent call last):
  File "/github/workspace/decisionengine/framework/engine/tests/fixtures.py", line 89, in de_server_factory
    proc_fixture = request.getfixturevalue(pg_prog_name)
  File "/github/workspace/venv/lib/python3.6/site-packages/_pytest/fixtures.py", line 572, in getfixturevalue
    fixturedef = self._get_active_fixturedef(argname)
  File "/github/workspace/venv/lib/python3.6/site-packages/_pytest/fixtures.py", line 592, in _get_active_fixturedef
    self._compute_fixture_value(fixturedef)
  File "/github/workspace/venv/lib/python3.6/site-packages/_pytest/fixtures.py", line 676, in _compute_fixture_value
    fixturedef.execute(request=subrequest)
  File "/github/workspace/venv/lib/python3.6/site-packages/_pytest/fixtures.py", line 1057, in execute
    result = hook.pytest_fixture_setup(fixturedef=self, request=request)
  File "/github/workspace/venv/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/github/workspace/venv/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/github/workspace/venv/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/github/workspace/venv/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/github/workspace/venv/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/github/workspace/venv/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/github/workspace/venv/lib/python3.6/site-packages/_pytest/fixtures.py", line 1111, in pytest_fixture_setup
    result = call_fixture_func(fixturefunc, request, kwargs)
  File "/github/workspace/venv/lib/python3.6/site-packages/_pytest/fixtures.py", line 908, in call_fixture_func
    fixture_result = next(generator)
  File "/github/workspace/venv/lib/python3.6/site-packages/pytest_postgresql/factories.py", line 164, in postgresql_proc_fixture
    with postgresql_executor:
  File "/github/workspace/venv/lib/python3.6/site-packages/mirakuru/base.py", line 172, in __enter__
    return self.start()
  File "/github/workspace/venv/lib/python3.6/site-packages/pytest_postgresql/executor.py", line 124, in start
    self.init_directory()
  File "/github/workspace/venv/lib/python3.6/site-packages/pytest_postgresql/executor.py", line 164, in init_directory
    subprocess.check_output(init_directory, env=env)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/pgsql-11/bin/pg_ctl', 'initdb', '--pgdata', '/tmp/postgresqldata.20577', '-o', '--username=postgres --auth=trust']' returned non-zero exit status 1.
---------------------------- Captured stderr setup -----------------------------
sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
initdb: invalid locale settings; check LANG and LC_* environment variables
pg_ctl: database system initialization failed
```

**Comment by jcpunk** [comment]
I'm betting the SL7 docker container is over cleaning up the locales...

**Comment by knoepfel** [comment]
@jcpunk, those are just messages logged to STDERR, and I've seen them before without much effect on the success of the unit test.  Do you expect that they have any bearing on the failure mode, which appears to be the call here:

```
File "/github/workspace/decisionengine/framework/engine/tests/fixtures.py", line 89, in de_server_factory
    proc_fixture = request.getfixturevalue(pg_prog_name)
```
which, under the covers is calling:
```
Command '['/usr/pgsql-11/bin/pg_ctl', 'initdb', '--pgdata', '/tmp/postgresqldata.20577', '-o', '--username=postgres --auth=trust']'
```
that ends in exit code 1?

**Comment by DmitryLitvintsev** [comment]
I think that :

```
sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
```

are "harmless" (at least I have seen them before, but test succeeded)

But this 

```
initdb: invalid locale settings; check LANG and LC_* environment variables
```

is fatal.

**Comment by jcpunk** [comment]
Per https://github.com/ClearcodeHQ/pytest-postgresql/commit/ff31a3f38bb92f7c92325db9f67941327849aa4f

It looks like pytest_postgresql is trying to explicitly set the lang environment.  I've seen databases get grumpy if they can't find the correct language files (it usually wants to know what "alphabetical" means to you).

**Comment by knoepfel** [comment]
Ah...thanks, @DmitryLitvintsev and @jcpunk.

**Comment by DmitryLitvintsev** [comment]
I have seen this suggested workaround along the lines:

```
initdb -D <your_data_location> --no-locale --encoding=UTF8
```

Not sure how these options can be invoked thtough pytest-postgresql

**Comment by jcpunk** [comment]
Ultimately the container shouldn't be shipping bad locales... that is on me.

Are you seeing the locale bug in non-container environments?

**Comment by jcpunk** [comment]
New containers deployed
